############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about-us"
weight = 2

[[main]]
name = "Curriculum"
url = "/curriculum"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Resources"
url = "/family-resources"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu

[[footer]]
name = "TOS"
url = "/tos"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
